name: dimbakenya
base_url: https://www.dimbakenya.com/%!(EXTRA string=dimbakenya)
browser_path: /usr/bin/chrome
username: user1
password: pass1
region: KE
selectors:
  login:
    username_input: input#username
    password_input: input#password
    login_button: button#login
  event_search:
    sport_dropdown: select#sport
    date_picker: input#date
    search_button: button#search
  odds_selector:
    moneyline: div.moneyline
    spread: div.spread
    totals: div.totals
bet_button: button#placeBet
bet_history: div#betHistory
live_betting:
  live_event: div.live-event
  in_play_bet_button: button#inPlayBet
