sportsbooks:
  - name: Bookie A
    base_url: https://sportsbook1.example.com
    browser_path: /path/to/chrome
    username: user1
    password: pass1
    region: EU
    selectors:
      login:
        username_input: input#username1
        password_input: input#password1
        login_button: button#login1
      event_search:
        sport_dropdown: select#sport1
        date_picker: input#date1
        search_button: button#search1
      odds_selector:
        moneyline: div.moneyline1
        spread: div.spread1
        totals: div.totals1
      bet_button: button#placeBet1
      bet_history: div#betHistory1
      live_betting:
        live_event: div.live-event1
        in_play_bet_button: button#inPlayBet1
  - name: Bookie B
    base_url: https://sportsbook2.example.com
    browser_path: /path/to/chrome
    username: user2
    password: pass2
    region: EU
    selectors:
      login:
        username_input: input#username2
        password_input: input#password2
        login_button: button#login2
      event_search:
        sport_dropdown: select#sport2
        date_picker: input#date2
        search_button: button#search2
      odds_selector:
        moneyline: div.moneyline2
        spread: div.spread2
        totals: div.totals2
      bet_button: button#placeBet2
      bet_history: div#betHistory2
      live_betting:
        live_event: div.live-event2
        in_play_bet_button: button#inPlayBet2
  - name: Bookie C
    base_url: https://sportsbook3.example.com
    browser_path: /path/to/chrome
    username: user3
    password: pass3
    region: EU
    selectors:
      login:
        username_input: input#username3
        password_input: input#password3
        login_button: button#login3
      event_search:
        sport_dropdown: select#sport3
        date_picker: input#date3
        search_button: button#search3
      odds_selector:
        moneyline: div.moneyline3
        spread: div.spread3
        totals: div.totals3
      bet_button: button#placeBet3
      bet_history: div#betHistory3
      live_betting:
        live_event: div.live-event3
        in_play_bet_button: button#inPlayBet3
