name: Update Config

on:
  push:
    branches:
      - secondary

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go program
        run: |
          go run diago.go

      - name: Check for changes
        run: |
          git diff --quiet config.yaml
          if [ $? -ne 0 ]; then
            echo "Changes detected"
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add config.yaml
            git commit -m "Update config.yaml"
            git push origin secondary
          else
            echo "No changes detected"
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update config.yaml"
          body: "Automated update to config.yaml"
          base: "main"
          head: "secondary"
